# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='count',
        ),
    ]
