# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_remove_poke_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
